version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:474007463914:task-definition/pensioner-details-task:1"
        LoadBalancerInfo:
          ContainerName: "pensioner-details"
          ContainerPort: "8080"
        PlatformVersion: "LATEST"